# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{right_support}
  s.version = "2.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tony Spataro", "Sergey Sergyenko", "Ryan Williamson", "Lee Kirchhoff", "Alexey Karpik", "Scott Messier"]
  s.date = %q{2013-01-26}
  s.description = %q{A toolkit of useful, reusable foundation code created by RightScale.}
  s.email = %q{support@rightscale.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/balancer_error_handling.feature",
    "features/balancer_health_check.feature",
    "features/continuous_integration.feature",
    "features/continuous_integration_cucumber.feature",
    "features/continuous_integration_rspec1.feature",
    "features/continuous_integration_rspec2.feature",
    "features/http_client_timeout.feature",
    "features/serialization.feature",
    "features/step_definitions/http_client_steps.rb",
    "features/step_definitions/request_balancer_steps.rb",
    "features/step_definitions/ruby_steps.rb",
    "features/step_definitions/serialization_steps.rb",
    "features/step_definitions/server_steps.rb",
    "features/support/env.rb",
    "features/support/file_utils_bundler_mixin.rb",
    "lib/right_support.rb",
    "lib/right_support/ci.rb",
    "lib/right_support/ci/java_cucumber_formatter.rb",
    "lib/right_support/ci/java_spec_formatter.rb",
    "lib/right_support/ci/rake_task.rb",
    "lib/right_support/config.rb",
    "lib/right_support/config/feature_set.rb",
    "lib/right_support/config/recursive_true_class.rb",
    "lib/right_support/config/yaml_config.rb",
    "lib/right_support/crypto.rb",
    "lib/right_support/crypto/signed_hash.rb",
    "lib/right_support/data.rb",
    "lib/right_support/data/hash_tools.rb",
    "lib/right_support/data/serializer.rb",
    "lib/right_support/data/uuid.rb",
    "lib/right_support/db.rb",
    "lib/right_support/db/cassandra_model.rb",
    "lib/right_support/log.rb",
    "lib/right_support/log/exception_logger.rb",
    "lib/right_support/log/filter_logger.rb",
    "lib/right_support/log/mixin.rb",
    "lib/right_support/log/multiplexer.rb",
    "lib/right_support/log/null_logger.rb",
    "lib/right_support/log/system_logger.rb",
    "lib/right_support/net.rb",
    "lib/right_support/net/address_helper.rb",
    "lib/right_support/net/dns.rb",
    "lib/right_support/net/http_client.rb",
    "lib/right_support/net/lb.rb",
    "lib/right_support/net/lb/health_check.rb",
    "lib/right_support/net/lb/round_robin.rb",
    "lib/right_support/net/lb/sticky.rb",
    "lib/right_support/net/request_balancer.rb",
    "lib/right_support/net/s3_helper.rb",
    "lib/right_support/net/ssl.rb",
    "lib/right_support/net/ssl/open_ssl_patch.rb",
    "lib/right_support/net/string_encoder.rb",
    "lib/right_support/rack.rb",
    "lib/right_support/rack/log_setter.rb",
    "lib/right_support/rack/request_logger.rb",
    "lib/right_support/rack/request_tracker.rb",
    "lib/right_support/ruby.rb",
    "lib/right_support/ruby/easy_singleton.rb",
    "lib/right_support/ruby/object_extensions.rb",
    "lib/right_support/ruby/string_extensions.rb",
    "lib/right_support/stats.rb",
    "lib/right_support/stats/activity.rb",
    "lib/right_support/stats/exceptions.rb",
    "lib/right_support/stats/helpers.rb",
    "lib/right_support/validation.rb",
    "lib/right_support/validation/openssl.rb",
    "lib/right_support/validation/ssh.rb",
    "right_support.gemspec",
    "right_support.rconf",
    "spec/config/feature_set_spec.rb",
    "spec/crypto/signed_hash_spec.rb",
    "spec/data/hash_tools_spec.rb",
    "spec/data/uuid_spec.rb",
    "spec/db/cassandra_model_part1_spec.rb",
    "spec/db/cassandra_model_part2_spec.rb",
    "spec/db/cassandra_model_spec.rb",
    "spec/fixtures/encrypted_priv_rsa.pem",
    "spec/fixtures/good_priv_dsa.pem",
    "spec/fixtures/good_priv_rsa.pem",
    "spec/fixtures/good_pub_dsa.ssh",
    "spec/fixtures/good_pub_rsa.pem",
    "spec/fixtures/good_pub_rsa.ssh",
    "spec/log/exception_logger_spec.rb",
    "spec/log/filter_logger_spec.rb",
    "spec/log/mixin_spec.rb",
    "spec/log/multiplexer_spec.rb",
    "spec/log/null_logger_spec.rb",
    "spec/log/system_logger_spec.rb",
    "spec/net/address_helper_spec.rb",
    "spec/net/balancing/health_check_spec.rb",
    "spec/net/balancing/round_robin_spec.rb",
    "spec/net/balancing/sticky_policy_spec.rb",
    "spec/net/dns_spec.rb",
    "spec/net/http_client_spec.rb",
    "spec/net/request_balancer_spec.rb",
    "spec/net/s3_helper_spec.rb",
    "spec/net/ssl_spec.rb",
    "spec/net/string_encoder_spec.rb",
    "spec/rack/log_setter_spec.rb",
    "spec/rack/request_logger_spec.rb",
    "spec/rack/request_tracker_spec.rb",
    "spec/ruby/easy_singleton_spec.rb",
    "spec/ruby/object_extensions_spec.rb",
    "spec/ruby/string_extensions_spec.rb",
    "spec/spec_helper.rb",
    "spec/stats/activity_spec.rb",
    "spec/stats/exceptions_spec.rb",
    "spec/stats/helpers_spec.rb",
    "spec/validation/openssl_spec.rb",
    "spec/validation/ssh_spec.rb"
  ]
  s.homepage = %q{https://github.com/rightscale/right_support}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Reusable foundation code.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, ["~> 0.9"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0.10"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0.11.6"])
      s.add_development_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.0"])
      s.add_development_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_development_dependency(%q<syntax>, ["~> 1.0.0"])
      s.add_development_dependency(%q<nokogiri>, ["~> 1.5"])
    else
      s.add_dependency(%q<rake>, ["~> 0.9"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10"])
      s.add_dependency(%q<ruby-debug19>, [">= 0.11.6"])
      s.add_dependency(%q<rdoc>, [">= 2.4.2"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<cucumber>, ["~> 1.0"])
      s.add_dependency(%q<flexmock>, ["~> 0.8"])
      s.add_dependency(%q<syntax>, ["~> 1.0.0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.5"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 0.9"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10"])
    s.add_dependency(%q<ruby-debug19>, [">= 0.11.6"])
    s.add_dependency(%q<rdoc>, [">= 2.4.2"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<cucumber>, ["~> 1.0"])
    s.add_dependency(%q<flexmock>, ["~> 0.8"])
    s.add_dependency(%q<syntax>, ["~> 1.0.0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.5"])
  end
end

