Given /^a Ruby application$/ do
  ruby_app_root.should_not be_nil
end

Given /^a Gemfile$/ do
  gemfile = ruby_app_path('Gemfile')
  unless File.exist?(gemfile)
    basedir = File.expand_path('../../..', __FILE__)
    File.open(gemfile, 'w') do |file|
      file.puts "gem 'right_support', :path=>'#{basedir}'"
    end
  end
end

Given /^a gem dependency on '(.*)'$/ do |dependency|
  Given 'a Gemfile'
  gem, version = dependency.split(/\s+/, 2)
  gemfile = ruby_app_path('Gemfile')
  File.open(gemfile, 'a') do |file|
    file.puts "gem '#{gem}', '#{version}'"
  end
end

Given /^a Rakefile$/ do
  rakefile = ruby_app_path('Rakefile')
  unless File.exist?(rakefile)
    File.open(rakefile, 'w') do |file|
      file.puts "# Auto-generated by #{__FILE__}"
    end
  end
end

Given /^the Rakefile contains a RightSupport::CI::RakeTask$/ do
  Given 'a Rakefile'
  rakefile = ruby_app_path('Rakefile')
  File.open(rakefile, 'w') do |file|
    file.puts "require 'right_support/ci/rake_task'"
    file.puts "RightSupport::CI::RakeTask.new"
  end
end

Given /^a trivial RSpec spec$/ do
  spec_dir = ruby_app_path('spec')
  spec = ruby_app_path('spec', 'trivial_spec.rb')
  FileUtils.mkdir_p(spec_dir)
  unless File.exist?(spec)
    File.open(spec, 'w') do |file|
      file.puts "describe String do"
      file.puts "  it 'has a size' do"
      file.puts "    'joe'.size.should == 3"
      file.puts "  end"
      file.puts "end"
    end
  end
end

When /^I install the bundle$/ do
  ruby_app_shell('bundle install')
end

When /^I rake '(.*)'$/ do |task|
  @ruby_app_output = ruby_app_shell("rake --trace #{task}")
end

Then /^the output should contain '(.*)'$/ do |expected_output|
  @ruby_app_output.index(expected_output).should_not be_nil
end

Then /^the directory '(.*)' should contain files/ do |dir|
  dir = ruby_app_path(dir)
  File.directory?(dir).should be_true
  Dir[File.join(dir, '*')].should_not be_empty
end